version: '3.3'
services:
    postgres:
        build:
            context: ./modules/postgresql
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        volumes:
            - ${POSTGRES_HOST_DATA}:/var/lib/postgresql/data
        restart: always
        environment:
            - POSTGRES_TRENCAT_USER
            - POSTGRES_TRENCAT_DB
    redis:
        build:
            context: ./modules/redis
            dockerfile: Dockerfile
        ports:
            - "6379:6379"
        volumes: # Only if storage is enabled in redis.conf
            - ${REDIS_HOST_DATA}:/data 
        restart: always
    influx:
        image: influxdb:1.7-alpine
        #build:
        #    context: ./modules/influx
        #    dockerfile: Dockerfile
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes:
            - ${INFLUX_HOST_DATA}:/var/lib/influxdb
        restart: always
        environment:
            - INFLUXDB_DB
    grafana:
        image: grafana/grafana:6.2.1
        ports:
            - "3000:3000"
        volumes:
            - ${GRAFANA_HOST_DATA}:/var/lib/grafana
        restart: always
        user: "472"
    logserver:
        #image: rsyslog/syslog_appliance_alpine
        build:
            context: ./modules/logserver
            dockerfile: Dockerfile
        ports:
            - "${LOGSERVER_TCP_PORT}:${LOGSERVER_TCP_PORT}"
        restart: always
        volumes:
            - ${LOGSERVER_DATA}:/var/log/trencat/
        environment:
            - LOGSERVER_TCP_PORT
        tty: true
        stdin_open: true

