- name: Check docker exists
  become: yes
  command: docker version
  register: docker_exists
  ignore_errors: yes

- name: Install software
  when: docker_exists is failed
  become: yes
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-client
    - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker GPG key
  when: docker_exists is failed
  become: yes
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Add Docker APT repository
  when: docker_exists is failed
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker
  when: docker_exists is failed
  become: yes
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    update_cache: yes
