- name: Install git
  become: yes
  apt:
    name:
    - git
    - tig
    state: present
    update_cache: yes

- name: Show current branch in prompt
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    backup: yes
    state: present
    block: |
        # Show git branch in prompt
        parse_git_branch() {
            git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
        }
        export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "
