- name: Check visual studio code exists
  command: code --version
  register: vscode_exists
  ignore_errors: yes

- name: Install vscode dependencies
  when: vscode_exists is failed
  become: yes
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    state: present
    update_cache: yes

- name: Add vscode GPG key
  when: vscode_exists is failed
  become: yes
  apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

- name: Add vscode APT repository
  when: vscode_exists is failed
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install vscode
  when: vscode_exists is failed
  become: yes
  apt:
    name: code
    update_cache: yes
